name = "ExtendedDates"
uuid = "78f5a1cc-aa73-4dda-b6b2-4d6b1976988f"
authors = ["Lilith Hafner <Lilith.Hafner@gmail.com>", "MichelJuillard <michel.juillard@mjui.fr>"]
version = "0.2.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
Reexport = "1"
julia = "1.8"

[extras]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["InteractiveUtils", "Plots", "Test"]
